name: finals_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  table_calendar: ^3.0.2
  shelf: ^1.4.1
  shelf_router: ^1.0.0
  mysql1: ^0.20.0
  http: ^0.13.6
  path: ^1.8.0
  sqflite: ^2.0.0+4

flutter:
  uses-material-design: true
